name = "duahtor"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "duahtor-waitlist"
database_id = "d47e71d8-ef37-470e-b6a3-8c966d45003a"